baseURL = "https://jsg-hohe-warte.de/"
languageCode = "de-de"
title = "JSG Hohe Warte"
enableRobotsTXT = true
toc = false
disableToc = true
showInThisSection = false      # Beispielname – siehe unten „finden“
showSectionMenu = false


[markup.goldmark.renderer]
  unsafe = true

[pagination]
  pagerSize = 10



