name: Build and Deploy (Hugo → GitHub Pages)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Detect GitHub Pages base URL
        id: pages
        shell: bash
        run: |
          REPO="${{ github.event.repository.name }}"
          OWNER="${{ github.repository_owner }}"
          if [[ "$REPO" == *.github.io ]]; then
            echo "base_url=https://${REPO}/" >> $GITHUB_OUTPUT
          else
            echo "base_url=https://${OWNER}.github.io/${REPO}/" >> $GITHUB_OUTPUT
          fi
          echo "Using base URL: $(cat $GITHUB_OUTPUT)"

      - name: Build
        run: hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: false
